### ISSUE TITLE
BERTの文献のタイポ

### ISSUE THREAD

**Issue by tomohideshibata** [stockmarkteam/bert-book#1]
P.6とP.41のBERTの文献内で、NACACL -> NAACL

**Comment by omitakahiro** [comment]
ご連絡いただきありがとうございます。こちらは、[誤植一覧](https://github.com/stockmarkteam/bert-book/blob/master/CORRECTION.md)に反映しましたので、クローズさせていただきます。

どうもありがとうございました。
