### ISSUE TITLE
P.107 固有表現のカテゴリー

### ISSUE THREAD

**Issue by tomohideshibata** [stockmarkteam/bert-book#10]
最後のIREXの固有表現のカテゴリーに固有物名がぬけています。

**Comment by omitakahiro** [comment]
ご連絡いただきありがとうございます。こちらは、[誤植一覧](https://github.com/stockmarkteam/bert-book/blob/master/CORRECTION.md)に反映しましたので、クローズさせていただきます。

どうもありがとうございました。
