### ISSUE TITLE
P.28 図2.6(a)がない

### ISSUE THREAD

**Issue by chavatake** [stockmarkteam/bert-book#12]
P.28の一行目にて、図2.6(a)を参照していますが、図2.6の中に(a)が見当たらないように思います。

**Comment by omitakahiro** [comment]
ご連絡いただきありがとうございます。図2.6(a)は図2.6の間違えでした。どうも申し訳ありません。

こちらは、[誤植一覧](https://github.com/stockmarkteam/bert-book/blob/master/CORRECTION.md)に反映しましたので、クローズさせていただきます。
