### ISSUE TITLE
p.72 scoresの表示

### ISSUE THREAD

**Issue by dkawahara** [stockmarkteam/bert-book#17]
#6-5 において、分類スコア(scores)を表示しようとしていますが、scoresのsizeを表示しています。また、コードでは"# scores:"を表示していますが、出力結果では"# size:"が出力されています。

**Comment by omitakahiro** [comment]
誤植をご連絡いただき、ありがとうございます。また、他の箇所も細かいところまで見ていただき、ありがとうございました。とても助かりました。

こちらは、[誤植一覧](https://github.com/stockmarkteam/bert-book/blob/master/CORRECTION.md)に反映しましたので、クローズさせていただきます。
