### ISSUE TITLE
P.12 図2.1のReLU

### ISSUE THREAD

**Issue by tomohideshibata** [stockmarkteam/bert-book#2]
P.12の図2.1(b)のReLUにおいて、x < 0でのyの値が0ではなく0より少し小さな値になっています。

**Comment by omitakahiro** [comment]
ご連絡いただきありがとうございます。こちらは、[誤植一覧](https://github.com/stockmarkteam/bert-book/blob/master/CORRECTION.md)に反映しましたので、クローズさせていただきます。

どうもありがとうございました。
