### ISSUE TITLE
p.85 タイポ: best_model_score

### ISSUE THREAD

**Issue by dkawahara** [stockmarkteam/bert-book#20]
本文の後から2行目: checkpoint.bert_model_path -> checkpoint.best_model_score

**Comment by omitakahiro** [comment]
誤植をご連絡いただき、ありがとうございます。また、他の箇所も細かいところまで見ていただき、ありがとうございました。とても助かりました。

こちらは、[誤植一覧](https://github.com/stockmarkteam/bert-book/blob/master/CORRECTION.md)に反映しましたので、クローズさせていただきます。
