### ISSUE TITLE
p.83 training_step と train_step

### ISSUE THREAD

**Issue by chavatake** [stockmarkteam/bert-book#21]
コードスニペット内ではtraining_stepとなっていますが、文章中ではtrain_stepとして参照されています。

**Comment by omitakahiro** [comment]
誤植をご連絡いただき、ありがとうございます。とても助かりました。

こちらは、[誤植一覧](https://github.com/stockmarkteam/bert-book/blob/master/CORRECTION.md)に反映しましたので、クローズさせていただきます。
