### ISSUE TITLE
P.121 タイポ BertForToeknClassification

### ISSUE THREAD

**Issue by chavatake** [stockmarkteam/bert-book#22]
BertForToeknClassification -> BertForTokenClassification と思われます。

同じタイポが3箇所あります。
本文の3行目と4行目、及び図8.2のキャプションです。

**Comment by omitakahiro** [comment]
誤植をご連絡いただき、ありがとうございます。また、毎回ご報告いただきありがとうございます。とても助かっています！

こちらは、[誤植一覧](https://github.com/stockmarkteam/bert-book/blob/master/CORRECTION.md)に反映しましたので、クローズさせていただきます。
