### ISSUE TITLE
P.37最終行

### ISSUE THREAD

**Issue by kskkoba** [stockmarkteam/bert-book#23]
とてもわかりやすい書籍の出版ありがとうございます。
P.37の最終行にある、e^S_iですが、e^P_iの誤りではないかと思いご連絡させていただきました。
ご確認いただければと思います。

**Comment by omitakahiro** [comment]
誤植をご連絡いただき、ありがとうございます。ご指摘の通りです。とても助かります。

また、ご感想もいただきありがとうございます。とても励みになります。

こちらは、[誤植一覧](https://github.com/stockmarkteam/bert-book/blob/master/CORRECTION.md)に反映しましたので、クローズさせていただきます。
