### ISSUE TITLE
p.179 タイポ

### ISSUE THREAD

**Issue by ryuichit** [stockmarkteam/bert-book#25]
p.179の中段、 「アルゴリズムをを」->「アルゴリズムを」。

**Comment by omitakahiro** [comment]
誤植をご連絡いただき、ありがとうございます。とても助かりました。

こちらは、[誤植一覧](https://github.com/stockmarkteam/bert-book/blob/master/CORRECTION.md)に反映しましたので、クローズさせていただきます。
