### ISSUE TITLE
p27 損失関数

### ISSUE THREAD

**Issue by ykskks** [stockmarkteam/bert-book#26]
「次の損失関数、」とありますが、式自体は尤度関数になっているようです。

論文の該当箇所を確認しましたが、

> Our formulation jointly maximizes the log
likelihood of the forward and backward directions:

とありましたので、「損失関数」を「（対数）尤度関数」に変更する、もしくは「損失関数」の表記のままで式にマイナス記号をつけるのが適切ではないかと思いました。

**Comment by omitakahiro** [comment]
誤植をご連絡いただき、ありがとうございます。ご指摘の通りでした。「式の先頭にマイナスをつける」の対応をしたいと思います。とても助かりました。

こちらは、[誤植一覧](https://github.com/stockmarkteam/bert-book/blob/master/CORRECTION.md)に反映しましたので、クローズさせていただきます。
