### ISSUE TITLE
p36 タイポ

### ISSUE THREAD

**Issue by ykskks** [stockmarkteam/bert-book#28]
5. Feedforward Networkの2行目で、
Layer Normalizationであるべきところが「Layer Normalizatin」になっています。

**Comment by omitakahiro** [comment]
誤植をご連絡いただき、ありがとうございます。とても助かりました！

こちらは、[誤植一覧](https://github.com/stockmarkteam/bert-book/blob/master/CORRECTION.md)に反映しましたので、クローズさせていただきます。
