### ISSUE TITLE
【第6章】Pytorch Lightningの関数定義について(p.82〜83)

### ISSUE THREAD

**Issue by kawase621** [stockmarkteam/bert-book#44]
p.82〜83で実装している3つの関数training_step、validation_step、test_stepはそれぞれ引数として「batch」と「batch_index」の2つを受け取るようになっています。

その一方で、今回の学習において与えるデータは、データローダから取り出した段階では「batch_index」に相当するものが無いように思います。

「batch」に相当するデータのみを使ってtraining_step関数を実行してしまうと、普通は"missing 1 required positional argument"のような、必要な位置引数が不足していることを示すエラーを吐くと思うのですが、Pytorch Lightningではこの点をどのように扱っているのでしょうか？

trainer.fit()の実行時に「batch_index」に相当するデータが作られ、training_step関数に渡される？など色々考えて自分でも調べてみたのですが答えが見つからず、ご教示頂ければ助かります。

**Comment by omitakahiro** [comment]
pytorch_lightningがdataloaderからbatchを取り出す時に、batch_idxを自動的に生成し、それをtraining_stepなどの関数に渡していると思われます。実際に、training_stepの中に、`print(batch_idx)`のコードを入れて、trainer.fit()を実行すると、batch_idxが適切に入力されていることがわかります。

**Comment by kawase621** [comment]
早速のご回答ありがとうございます。
やはりtrainer.fit()実行時のどこかでbatch_indexは自動的に作られるんですね。
納得しました。
