### ISSUE TITLE
#5-8　２つ以上の[MASK]を含む文章のときに起きている問題

### ISSUE THREAD

**Issue by ranboooo** [stockmarkteam/bert-book#52]
出力時に
今日は[MASK]へ行く。
という文章になってしまい、
[MASK]が残る原因がわからない状況です。

またトークナイザとモデルをロードしたときに
Some weights of the model checkpoint at cl-tohoku/bert-base-japanese-whole-word-masking were not used when initializing BertForMaskedLM: ['cls.seq_relationship.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
という警告文が表示されており、原因がわからないです。
解決できる方がいましたら、助けていただきたいです。

**Comment by omitakahiro** [comment]
5章のノートブックをColabで実行すると#5-8は、きちんと動作しているようですので、こちらを確認いただけるでしょうか？

https://colab.research.google.com/github/stockmarkteam/bert-book/blob/master/Chapter5.ipynb

警告文については、書籍が出版された後に表示されるようになったようですが、動作には問題ないようです。

**Comment by ranboooo** [comment]
Colabで動作することができました。ありがとうございます。
今回の問題は、自分がJupyterLabを使用しており、
必要なライブラリーが足りていないため
起こっている問題なのかもしれないです
